export const environment: any = {
  production: true,
  serviceBaseUrl: "https://api-test.tela-botanica.org/service:del:0.1/",
  serviceUtilisateursBaseUrl: "https://api-test.tela-botanica.org/service:del:0.1/",
  serviceAuthBaseUrl: "https://beta.tela-botanica.org/service:annuaire:auth/",
  bogueUrl: "http://taiga.tela-botanica.net",
  commentaireUrl: "https://www.tela-botanica.org/wikini/eflore-test/wakka.php?wiki=AideDelCommentaire",
  delUrl: "https://beta.tela-botanica.org/del/war/del.html",
  // delUrl:"http://www.tela-botanica.org/appli:del",
  identiplanteUrl: "https://beta.tela-botanica.org/appli:identiplante",
  pictofloraUrl: "https://beta.tela-botanica.org/appli:pictoflora",
  appliSaisieUrl: "https://beta.tela-botanica.org/widget:cel:saisie?tag-img=aDeterminer&tag-obs=aDeterminer&titre=",
  appliSaisieProjetUrl: "https://beta.tela-botanica.org/widget:cel:saisie?tag-img={projet}&tag-obs={projet}",
  efloreTaxonUrl: "https://www.tela-botanica.org/referentiel-nn-num_nom",
  efloreUrl: "https://www.tela-botanica.org/eflore?referentiel=bdtfx",
  ouvragesFloreUrl: "https://www.tela-botanica.org/page:ouvrages_flore",
  bonnierPdaUrl: "https://www.tela-botanica.org/eflore-test/bonnierpda",
  clesDeterminationUrl: "https://www.tela-botanica.org/page:menu_379",
  rssUrl: "https://api-test.tela-botanica.org/service:del:0.1/syndication/commentaires/rss2?navigation.depart=0&navigation.limite=150",
  iconeTagBaseUrl: "https://www.tela-botanica.org/del/appli/img/icones_tags/",
  profilUrl: "https://beta.tela-botanica.org/profil:",
  inscriptionUrl: "https://beta.tela-botanica.org/inscription/",
  imagesUrl: "https://api-test.tela-botanica.org/img:",
  urlWidgetRemarques: 'https://www.tela-botanica.org/widget:reseau:remarques',
  telaUrl : "https://beta.tela-botanica.org/",
  cookieName: 'tb_auth_beta_test'
};
